.TH EIO_CLI 8 "May 25, 2012" "" "eio_cli"

.SH NAME
eio_cli \- EnhanceIO command line interface

.SH SYNOPSIS
.B eio_cli create
.I -d <src device> -s <SSD device> [-p <policy>] [-m <cache mode>] [-b <block size>] -c <cache name>
.br
.B eio_cli delete 
.I -c <cache name>
.br
.B eio_cli clean 
.I -c <cache name>
.br
.B eio_cli info 
.I
.br
.B eio_cli edit 
.I [-p <policy>] [-m <cache mode>] -c <cache name>
.br

.SH DESCRIPTION
.B EnhanceIO 
is a block device caching software that uses an SSD as cache for traditional HDDs. 
The eio_cli command line interface is intended to serve the purpose of administering the caches. 
The eio_cli command takes the first argument as a sub-command, rest of the arguments are options
specific to the sub-command. 

.SH SUB-COMMANDS
.SS "eio_cli create \fIoptions\fR"
.PP
Creates a new cache by associating an SSD device with a source device\&.
.PP
\-d \fR\fB\f\<source device>\fR\fR
.RS 4
Specifies the source device\&.
.RE
.PP
\-s \fR\fB\f\<SSD device>\fR\fR
.RS 4
Specifies the SSD device\&.
.RE
.PP
\-c \fR\fB\f\<Cache name >\fR\fR
.RS 4
Specifies the Cache name\&.
.RE
.PP
\fR\fB\f\[\-p <policy>]\fR\fR
.RS 4
Cache block replacement policy\&. Policies are: 
\fBlru\fR,
\fBfifo(default)\fR,
\fBrand(random)\fR\&.
.RE
.PP
\fR\fB\f\[\-m <cache mode>]\fR\fR
.RS 4
Specifies the caching mode\&. Supported caching modes are: 
\fBro(Read-Only)\fR,
\fBwt(default: Write-Through)\fR,
\fBwb(Write-Back)\fR\&.
.RE
.PP
\fR\fB\f\[\-b <block size>]\fR\fR
.RS 4
Specifies the block size of each single cache entry\&. Block size are:
\fB2048\fR,
\fB4096(default)\fR,
\fB8192\fR\&.
.RE
.PP
.SS "eio_cli delete \fIoptions\fR"
.RE
.PP
Deletes a pre-existing cache\&.
.RE
.PP
\-c \fR\fB\f\<Cache name>\fR\fR
.RS 4
Specifies the Cache name\&.
.RE
.PP
.SS "eio_cli clean \fIoptions\fR"
.RE
.PP
Cleans a pre-existing cache\&.
.RE
.PP
\-c \fR\fB\f\<Cache name>\fR\fR
.RS 4
Specifies the Cache name\&.
.PP
.RE
.SS "eio_cli info"
.PP
Displays information of existing cache devices\&.
.RE
.RE
.SS "eio_cli edit \fIoptions\fR"
.PP
Modifies the properties of a cache\&.
.RE
.PP
\-c \fR\fB\f\<Cache name>\fR\fR
.RS 4
Specifies the Cache name\&.
.RE
.PP
\fR\fB\f\[\-p <policy>]\fR\fR
.RS 4
Cache block replacement policy\&. Policies are: 
\fBlru\fR,
\fBfifo(default)\fR,
\fBrand(random)\fR\&.
.RE
.PP
\fR\fB\f\[\-m <cache mode>]\fR\fR
.RS 4
Specifies the caching mode\&. Supported caching modes are: 
\fBro(Read-Only)\fR,
\fBwt(Write-Through)\fR,
\fBwb(Write-Back)\fR\&.
.RE
.PP

.SH EXAMPLES

# Create a cache 
    $ eio_cli create \-d /dev/sdg \-s /dev/sdf \-p lru \-m wt \-c SDG_CACHE
    $ eio_cli create \-d /dev/sdm \-s /dev/sdk \-c SDM_CACHE
    $ eio_cli create \-d /dev/sdc1 \-s /dev/sdd1 \-c SDC1_CACHE

# Display properties of the cache devices 
    $ eio_cli info 

# Edit the properties of the cache SDG_CACHE
    $ eio_cli edit \-p fifo \-c SDG_CACHE
    $ eio_cli edit \-p rand \-m ro \-c SDG_CACHE

# Delete the cache SDG_CACHE
    $ eio_cli clean \-c SDG_CACHE

# Clean the cache SDG_CACHE
    $ eio_cli clean \-c SDG_CACHE



.SH AUTHOR
	\fRSTEC, Inc. \fI<http://www.stec-inc.com/>
Sanoj Unnikrishnan <sunnikrishnan@stec-inc.com>
